'use client';

import { useState, useEffect } from 'react';
import { AIUIRenderer } from '../components/AIUIRenderer';
import { aiUIClient, AIUIResponse } from '../lib/ai-ui-client';
import { ChevronDown, RefreshCw } from 'lucide-react';

export default function Home() {
  const [currentRole, setCurrentRole] = useState('viewer');
  const [activeView, setActiveView] = useState('products');
  const [uiResponse, setUIResponse] = useState<AIUIResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadAIUI();
  }, [currentRole, activeView]);

  const loadAIUI = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      let response: AIUIResponse;
      
      switch (activeView) {
        case 'products':
          response = await aiUIClient.getProductsUI(currentRole);
          break;
        case 'categories':
          response = await aiUIClient.getCategoriesUI(currentRole);
          break;
        case 'context':
          response = await aiUIClient.getUserContextUI(currentRole);
          break;
        default:
          response = await aiUIClient.getProductsUI(currentRole);
      }
      
      setUIResponse(response);
    } catch (error) {
      console.error('Failed to load AI UI:', error);
      setError(`Failed to load AI UI: ${error}`);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRoleChange = (newRole: string) => {
    setCurrentRole(newRole);
  };

  const handleUIAction = (action: string, data?: any) => {
    console.log('UI Action:', action, data);
    
    switch (action) {
      case 'delete_success':
      case 'form_success':
        // Refresh UI after successful operations
        loadAIUI();
        break;
      case 'form_error':
        setError(data?.error || 'An error occurred');
        break;
      case 'show_add_form':
        // Handle showing add form
        break;
      case 'go_home':
        // Reset to home state - clear UI response
        setUIResponse(null);
        setActiveView('products');
        setError(null);
        break;
      default:
        console.log('Unhandled action:', action);
    }
  };

  const handleViewChange = (newView: string) => {
    setActiveView(newView);
    // Clear UI response when switching to non-AI views like API tester
    if (newView === 'api') {
      setUIResponse(null);
      setError(null);
    }
  };

  const handleRefresh = () => {
    loadAIUI();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-4">
              <div className="w-8 h-8 ai-gradient rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">AI</span>
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900">AI Runtime Engine</h1>
                <p className="text-sm text-gray-600">Dynamic UI Generated by AI + Policies</p>
              </div>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">
                🤖 AI-Driven UI
              </div>
              <div className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-medium">
                Role: {currentRole}
              </div>
              <div className="bg-purple-100 text-purple-800 px-3 py-1 rounded-full text-sm font-medium">
                OpenAI Powered
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          
          {/* Left Sidebar - Controls */}
          <div className="lg:col-span-1">
            {/* Role Switcher */}
            <div className="bg-white rounded-lg shadow p-4 mb-6">
              <h3 className="font-medium text-gray-900 mb-3">Switch User Role</h3>
              <div className="space-y-2">
                {['admin', 'manager', 'viewer'].map((role) => (
                  <button
                    key={role}
                    onClick={() => handleRoleChange(role)}
                    className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-colors ${
                      currentRole === role
                        ? 'bg-blue-100 text-blue-700 font-medium'
                        : 'hover:bg-gray-100 text-gray-700'
                    }`}
                  >
                    {role.charAt(0).toUpperCase() + role.slice(1)}
                  </button>
                ))}
              </div>
            </div>

            {/* View Selector */}
            <div className="bg-white rounded-lg shadow p-4">
              <h3 className="font-medium text-gray-900 mb-3">AI Views</h3>
              <div className="space-y-2">
                {[
                  { key: 'products', label: '📦 Products' },
                  { key: 'categories', label: '📊 Categories' },
                  { key: 'context', label: '👤 User Context' },
                  { key: 'api', label: '🧪 API Tester' }
                ].map((view) => (
                  <button
                    key={view.key}
                    onClick={() => handleViewChange(view.key)}
                    className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-colors ${
                      activeView === view.key
                        ? 'bg-blue-100 text-blue-700 font-medium'
                        : 'hover:bg-gray-100 text-gray-700'
                    }`}
                  >
                    {view.label}
                  </button>
                ))}
              </div>
              
              <button
                onClick={handleRefresh}
                className="w-full mt-4 flex items-center justify-center space-x-2 px-3 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm text-gray-700 transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                <span>Refresh AI UI</span>
              </button>
            </div>
          </div>

          {/* Main Content Area */}
          <div className="lg:col-span-3">

            {/* Loading State */}
            {isLoading && (
              <div className="bg-white rounded-lg shadow p-8 text-center">
                <div className="w-16 h-16 mx-auto mb-4 bg-gray-100 rounded-full flex items-center justify-center">
                  <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                </div>
                <h3 className="text-lg font-semibold mb-2">AI is generating your UI...</h3>
                <p className="text-gray-600">Creating dynamic interface for {currentRole} role</p>
              </div>
            )}

            {/* Error State */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-6">
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-red-100 text-red-700 rounded-lg flex items-center justify-center">
                    <span className="text-sm font-bold">!</span>
                  </div>
                  <div>
                    <h3 className="font-semibold text-red-800">AI UI Generation Error</h3>
                    <p className="text-red-700 text-sm mt-1">{error}</p>
                  </div>
                </div>
                <button
                  onClick={handleRefresh}
                  className="mt-4 px-4 py-2 bg-red-100 hover:bg-red-200 text-red-700 rounded-lg text-sm font-medium transition-colors"
                >
                  Try Again
                </button>
              </div>
            )}

            {/* AI-Driven UI Content */}
            {!isLoading && !error && uiResponse && activeView !== 'api' && (
              <AIUIRenderer
                components={uiResponse.ui_config.components}
                navigation={uiResponse.ui_config.navigation}
                theme={uiResponse.ui_config.theme}
                layout={uiResponse.ui_config.layout}
                userRole={currentRole}
                onAction={handleUIAction}
                embedded={true}
              />
            )}

            {/* API Tester View */}
            {activeView === 'api' && (
              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="font-semibold mb-4">🧪 Dynamic API Tester</h3>
                <div className="space-y-4">
                  <div className="bg-yellow-50 border border-yellow-200 rounded p-4">
                    <p className="text-sm text-yellow-700">
                      This shows how the AI handles ANY request dynamically. Try different endpoints and see how the AI responds based on your role ({currentRole}).
                    </p>
                  </div>
                  
                  <div className="space-y-4">
                    {[
                      { method: 'GET', path: '/api/products', desc: 'Get products (all roles)' },
                      { method: 'POST', path: '/api/products', desc: 'Add product (admin/manager only)', requiresBody: true },
                      { method: 'DELETE', path: '/api/products/p1', desc: 'Delete product (admin only)' },
                      { method: 'GET', path: '/api/categories', desc: 'Get category analytics (manager/admin only)' },
                      { method: 'GET', path: '/api/user-context/' + currentRole, desc: 'Get user context' },
                      { method: 'GET', path: '/api/user-context/admin', desc: 'Get admin context (test access)' },
                      { method: 'GET', path: '/api/user-context/manager', desc: 'Get manager context (test access)' },
                      { method: 'GET', path: '/api/user-context/viewer', desc: 'Get viewer context (test access)' },
                      { method: 'GET', path: '/api/health', desc: 'Health check endpoint' },
                      { method: 'GET', path: '/api/demo-info', desc: 'Demo information' },
                      { method: 'GET', path: '/api/unknown-endpoint', desc: 'Test unknown endpoint (should return AI response)' },
                      { method: 'POST', path: '/api/random-endpoint', desc: 'Test POST to unknown endpoint' }
                    ].map((api, idx) => (
                      <div key={idx} className="border border-gray-200 rounded-lg">
                        <div className="p-4 bg-gray-50 border-b">
                          <div className="flex items-center justify-between">
                            <div>
                              <div className="font-medium text-gray-900">{api.method} {api.path}</div>
                              <div className="text-sm text-gray-600 mt-1">{api.desc}</div>
                            </div>
                            <div className="flex space-x-2">
                              <button
                                onClick={() => {
                                  window.open(
                                    `http://localhost:8000${api.path}`,
                                    '_blank'
                                  );
                                }}
                                className="px-3 py-1 bg-blue-100 hover:bg-blue-200 text-blue-700 rounded text-sm font-medium transition-colors"
                              >
                                🔗 Open
                              </button>
                              <button
                                onClick={async () => {
                                  try {
                                    const requestBody = api.requiresBody ? {
                                      name: 'Test Product',
                                      category: 'Electronics',
                                      price: 99.99,
                                      stock: 10
                                    } : undefined;

                                    const response = await fetch(`http://localhost:8000${api.path}`, {
                                      method: api.method,
                                      headers: {
                                        'X-User-Role': currentRole,
                                        'Content-Type': 'application/json'
                                      },
                                      ...(requestBody && { body: JSON.stringify(requestBody) })
                                    });
                                    const data = await response.json();
                                    
                                    // Show result in a simple modal/alert for now
                                    const resultWindow = window.open('', '_blank', 'width=800,height=600');
                                    if (resultWindow) {
                                      resultWindow.document.write(`
                                        <html>
                                          <head><title>API Response</title></head>
                                          <body style="font-family: monospace; padding: 20px;">
                                            <h3>${api.method} ${api.path}</h3>
                                            <p><strong>Status:</strong> ${response.status}</p>
                                            <p><strong>Role:</strong> ${currentRole}</p>
                                            <pre style="background: #f5f5f5; padding: 15px; border-radius: 5px; overflow: auto;">${JSON.stringify(data, null, 2)}</pre>
                                          </body>
                                        </html>
                                      `);
                                    }
                                  } catch (error) {
                                    alert(`Error: ${error}`);
                                  }
                                }}
                                className="px-3 py-1 bg-green-100 hover:bg-green-200 text-green-700 rounded text-sm font-medium transition-colors"
                              >
                                🧪 Test
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Welcome State */}
            {!isLoading && !error && !uiResponse && activeView !== 'api' && (
              <div className="bg-white rounded-lg shadow p-8 text-center">
                <div className="w-16 h-16 mx-auto mb-4 bg-gray-100 rounded-full flex items-center justify-center">
                  <span className="text-2xl">🤖</span>
                </div>
                <h3 className="text-lg font-semibold mb-2">AI UI Engine Ready</h3>
                <p className="text-gray-600 mb-4">
                  Select a view from the sidebar to generate your AI-driven interface for <strong>{currentRole}</strong> role.
                </p>
                <div className="text-sm text-gray-500">
                  Current view: {activeView} • Click "Refresh AI UI" to generate components
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-white border-t mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="text-center text-sm text-gray-500">
            <p>🤖 AI-Driven UI Generation | 🚀 Dynamic Components | 🎯 Policy-Based Interface</p>
          </div>
        </div>
      </footer>
    </div>
  );
}